sudo: false
language: node_js

node_js:
  - '8'

# fail asap when there is a failure
matrix:
  fast_finish: true

# cache node modules
cache:
  directories:
    - node_modules

before_install:
  # remove useless/non listed deps
  - npm prune
  # faster npm install
  - npm set progress=false

script: npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: dist
  on:
    branch: master